# Generated by Django 4.0.3 on 2022-03-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255)),
                ('structure_value', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='search_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('conversion_value', models.FloatField(max_length=255)),
                ('conversions', models.CharField(max_length=255)),
                ('search_term', models.CharField(max_length=500)),
                ('roas', models.FloatField(default=0.04)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roas.ad_group')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roas.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='ad_group',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roas.campaign'),
        ),
    ]
